version: 2.1
jobs:
  first_job:
    dokcer:
      - image: kt2505/second-image:latest
    steps:
      - checkout
      - run:
        name: install library
        command: npm install
  second_job:
    docker: 
      - image: kt2505/second-image:latest
    steps:
      - checkout
      - run:
        name: run project
        command: npm run start

workflows:
  version: 2
  install_lib:
    jobs:
      - first_job
  run_project:
    jobs:
      - second_job